### PR TITLE
fix: correctly display icons from absolute paths

### PR DESCRIPTION
**Pull request by hypeedev**

### CODE REVIEW

**Review by adamperkowski — DISMISSED** [review]
polska gurom

**Comment by nnyyxxxx** [comment]
screenshots please, doesn't seem to do anything for me

**Comment by adamperkowski** [comment]
I was about to say, the code is OK, don't know what the issue is tho.

**Comment by abenz1267** [comment]
If the icon path is absolute, hyprlauncher will display a broken icon. this pr tries to fix this.

it's not hard to understand.

**Review by nnyyxxxx — APPROVED** [review]

**Comment by adamperkowski** [comment]
why did you dismiss my review lol

**Pull request merged**
