### PR TITLE
🔎 feat: COOL dynamic search placeholder text

### PR DESCRIPTION
**Pull request by adamperkowski**

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
make it togglable in the config file should be off by default

**Review by nnyyxxxx — CHANGES_REQUESTED** [review]
only the enter tooltip should be togglable, not the "Press /" tooltip

**Comment by adamperkowski** [comment]
> only the enter tooltip should be togglable, not the "Press /" tooltip

you and your tooltip fantasies...

**Comment by nnyyxxxx** [comment]
press / to start searching should not show when the search bar is selected

**Comment by adamperkowski** [comment]
> press / to start searching should not show when the search bar is selected

it does not

**Comment by nnyyxxxx** [comment]
> > press / to start searching should not show when the search bar is selected
> 
> it does not

it does

**Comment by nnyyxxxx** [comment]
click escape and then / again to reproduce

**Comment by adamperkowski** [comment]
> click escape and then / again to reproduce

i did, i am, cannot reproduce

**Pull request closed without merging**
