### PR TITLE
add text color customization for hover and selected item

### PR DESCRIPTION
**Pull request by timoxa0**

### CODE REVIEW

**Review by nnyyxxxx — CHANGES_REQUESTED** [review]
"item_name_hover": "#000000",

is redundant

**Comment by nnyyxxxx** [comment]
all hovers are redundant

**Comment by timoxa0** [comment]
ok, now one value is used for hover and selection

**Comment by nnyyxxxx** [comment]
the new values should adopt gtk theming in the relevant gtk css section as well

**Comment by timoxa0** [comment]
done!

**Comment by nnyyxxxx** [comment]
i'm confused on what

"search_bg_focused"

is supposed to be, doesnt seem to work for me

**Comment by timoxa0** [comment]
it's not my change, i only added item_description_selected, item_description_selected and item_path_selected, but it is broken for me too

**Comment by nnyyxxxx** [comment]
ohh, :joy: sorry

**Review by nnyyxxxx — APPROVED** [review]

**Comment by adamperkowski** [comment]
EVEN MORE CONFIG CHANGES?! :despair:

**Pull request merged**
