### PR TITLE
perf: clean up the deps

### PR DESCRIPTION
**Pull request by adamperkowski**

### CODE REVIEW

**Comment by adamperkowski** [comment]
ugh conflicts

**Comment by nnyyxxxx** [comment]
i already did it

**Comment by nnyyxxxx** [comment]
drop every other change other than the toml and lock

**Comment by nnyyxxxx** [comment]
https://github.com/hyprutils/hyprlauncher/commit/e3cd41e9378aa8d47bd8e5fe9eeb0e5545609cb0

**Review by nnyyxxxx — APPROVED** [review]

**Comment by adamperkowski** [comment]
> drop every other change other than the toml and lock

dont tell me what to do ~bitch~

**Pull request merged**
